add:task
ClevertecFrontendLab/sprint1-ArtOfImpact pull request #1
Opened 2023-01-31 17:13 UTC by ArtOfImpact

2023-01-31 17:16 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675185419/content-window.png)

2023-01-31 17:32 UTC, Gaurrus requested changes

2023-01-31 17:32 UTC, Gaurrus commented on src/books.js
> +import book from "./photo/image/image.svg"
![image](https://user-images.githubusercontent.com/85307211/215836348-321150bc-444c-463a-9e35-5baebd8f4bee.png)
отзывы где? замокать и сделать как в макете

2023-01-31 17:32 UTC, Gaurrus commented on src/books.js
> +import cat_big from "./photo/image/cat-big.svg"
![image](https://user-images.githubusercontent.com/85307211/215836822-7cc79b01-7df7-4fee-b7b2-62b7689fcd48.png)
не по дизайну

2023-01-31 17:32 UTC, Gaurrus commented on src/books.js
> +import book_big from "./photo/image/image-big.svg"
![image](https://user-images.githubusercontent.com/85307211/215837797-bf6c399a-9fe2-44fb-b1f4-2433f9d32beb.png)
если не заполнене последний ряд, все элементы сместить влево, это для 768 ширины, полноэкранный сделал нормально)

2023-01-31 18:36 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675190219/content-window.png)

2023-01-31 18:49 UTC, Gaurrus requested changes

2023-01-31 18:49 UTC, Gaurrus commented on src/books.js
> +import cat_big from "./photo/image/cat-big.svg"
не исправлено

2023-01-31 19:28 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675193335/content-window.png)

2023-01-31 19:50 UTC, Gaurrus requested changes

2023-01-31 19:50 UTC, Gaurrus commented on src/pages/book/about/about-colum.module.css
> +} */
комментарии не допускай в готовом задании)

2023-01-31 19:50 UTC, Gaurrus commented on src/pages/main/content/content-aside/content-aside.module.css
> +    line-height: 28px;
чтобы не писать всё вот это каждому элементу, обычно задают родительноскому все общие свойства, дочерние элементы их наследуют

2023-01-31 19:50 UTC, Gaurrus commented on src/pages/main/content/content-header/content-header.jsx
> +                }} />
инлайновые стили никуда не годятся, всё переделать через css

2023-01-31 19:50 UTC, Gaurrus commented on src/pages/main/content/main-content.jsx
> +    const [Button, setButton] = useState(true)
булевый стейт обычно именуют через `isButton, setIsButton`

2023-02-01 09:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/ArtOfImpact/1675245231/content-window.png)

2023-02-01 11:34 UTC, Gaurrus approved these changes

2023-02-01 11:38 UTC, merged